name: Bug report
description: Report a reproducible problem with Lopper.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide enough detail to reproduce and verify a fix.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Reproduction steps
      description: Exact commands and files needed to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and output
      description: Paste CLI output, stack traces, or JSON snippets.
      render: shell

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Git SHA or release version.
      placeholder: e.g. 3fc8d60
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Go version, and relevant tooling versions.
      placeholder: macOS 14, Go 1.25.7, Node 22
    validations:
      required: true

