name: Feature request
description: Propose an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea.
        Focus on user problem, expected behavior, and success criteria.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user pain does this solve?
      placeholder: As a ..., I need ... because ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe behavior, CLI flags, output changes, or UX.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options and why they are less suitable.

  - type: textarea
    id: impact
    attributes:
      label: Impact and scope
      description: Affected adapters, performance, compatibility, docs, tests.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What must be true for this to be considered done?
      placeholder: |
        - [ ] ...
        - [ ] ...

