import subprocess
import unittest
from unittest.mock import patch

import source_size_report as report


class SourceSizeReportTest(unittest.TestCase):
    def test_exclusive_categories(self):
        cases = {
            'internal/a.go': 'production',
            'extensions/vscode-lopper/src/extension.ts': 'production',
            'scripts/check.sh': 'production',
            'internal/a_test.go': 'tests',
            'internal/testutil/fixture.go': 'tests',
            'internal/testsupport/harness.go': 'tests',
            'scripts/test_example.py': 'tests',
            'extensions/vscode-lopper/src/test/suite/extension.test.ts': 'tests',
            'extensions/vscode-lopper/test-fixtures/lopper-smoke-binary.mjs': 'fixtures',
            'extensions/vscode-lopper/test-fixtures/smoke-workspace/src/index.ts': 'fixtures',
            'extensions/vscode-lopper/test-fixtures/smoke-workspace/package.json': 'fixtures',
            'internal/testdata/a_test.go': 'fixtures',
            'vendor/pkg/a.go': 'generated_dependencies',
            'assets/library.min.js': 'generated_dependencies',
            'extensions/vscode-lopper/out/extension.js': 'generated_dependencies',
            'node_modules/package/package-lock.json': 'lockfiles',
            'go.sum': 'lockfiles',
            'docs/guide.md': 'configuration_docs',
            '.github/workflows/ci.yml': 'configuration_docs',
            'unknown.xyz': 'configuration_docs',
        }
        for name, expected in cases.items():
            with self.subTest(name=name):
                self.assertEqual(report.classify(name, b''), expected)
        self.assertEqual(report.classify('internal/generated.go', b'// Code generated by tool. DO NOT EDIT.\n'), 'generated_dependencies')

    def test_generated_marker_literals_do_not_hide_source_or_tests(self):
        marker_code = b"marker = b'Code generated' + b'DO NOT EDIT'\n"
        self.assertEqual(report.classify('scripts/report.py', marker_code), 'production')
        self.assertEqual(report.classify('scripts/report_test.py', marker_code), 'tests')
        self.assertEqual(report.classify('internal/report.go',
                         b'package report\nvar example = `\n// Code generated by tool. DO NOT EDIT.\n`\n'), 'production')
        self.assertEqual(report.classify('internal/generated.go',
                         b'// License header\n\n// Code generated by tool. DO NOT EDIT.\r\npackage report\n'), 'generated_dependencies')

    def test_extensionless_script_is_source(self):
        self.assertEqual(report.classify('.githooks/pre-commit', b'#!/bin/sh\n'), 'production')
        self.assertEqual(report.counts([('.githooks/pre-commit', b'100755', b'#!/bin/sh\n')])['production']['source_files'], 1)

    def test_physical_and_nonblank_lines(self):
        files = [('a.go', b'100644', b'first\r\n \t\r\nlast'),
                 ('empty.go', b'100644', b''),
                 ('binary.go', b'100644', b'\0\n'),
                 ('link.go', b'120000', b'outside.go')]
        result = report.counts(files)['production']
        self.assertEqual(result, dict(files=4, source_files=2, physical_lines=3, nonblank_lines=2, binary_files=1, symlinks=1))

    def test_helper_and_behavioral_contexts_remain_distinct(self):
        result = report.clone_context('a_test.go:2-3: duplicate of b_test.go:2-3', {
            'a_test.go': b'func makeFixture(t *testing.T) {\n x()\n}',
            'b_test.go': b'func TestBehavior(t *testing.T) {\n x()\n}',
        })
        self.assertEqual([item['kind'] for item in result['contexts']], ['helper_candidate', 'behavioral_case'])

    def test_clone_plumbing_preserves_groups_and_sorts_deterministically(self):
        files = [(name, b'100644', f'package example\nfunc Test{name[:-8]}(t *testing.T) {{}}\n'.encode())
                 for name in ('a_test.go', 'b_test.go', 'c_test.go', 'd_test.go')]
        def run(command, **kwargs):
            if command[0] == 'go':
                return subprocess.CompletedProcess(command, 0, stdout='', stderr='')
            root = str(__import__('pathlib').Path(command[0]).parent.parent)
            output = (
                f'{root}/b_test.go:5-6\n{root}/a_test.go:3-4\n\n'
                f'{root}/d_test.go:7-8\n{root}/c_test.go:1-2\n\n\n'
            )
            return subprocess.CompletedProcess(command, 0, stdout=output, stderr='')

        with patch.object(report.subprocess, 'run', side_effect=run):
            groups = report.test_clones(files, 'v1.0.0', 55)

        self.assertEqual(len(groups), 2)
        self.assertEqual([[context['path'] for context in group['contexts']] for group in groups],
                         [['a_test.go', 'b_test.go'], ['c_test.go', 'd_test.go']])

    def test_clone_diagnostics_fail_even_with_zero_exit(self):
        files = [('a_test.go', b'100644', b'package example\nfunc broken(')]
        success = subprocess.CompletedProcess([], 0, stdout='', stderr='')
        parse_error = subprocess.CompletedProcess([], 0, stdout='', stderr='a_test.go:2: expected identifier')
        with patch.object(report.subprocess, 'run', side_effect=[success, parse_error]) as run:
            with self.assertRaisesRegex(RuntimeError, 'expected identifier'):
                report.test_clones(files, 'v1.0.0', 55)
        self.assertEqual(run.call_args.kwargs['stderr'], subprocess.PIPE)

    def test_support_sources_participate_in_clone_analysis(self):
        files = [('internal/testutil/fixture.go', b'100644', b'package testutil\n'),
                 ('internal/testsupport/harness.go', b'100644', b'package testsupport\n'),
                 ('internal/production.go', b'100644', b'package internal\n')]
        success = subprocess.CompletedProcess([], 0, stdout='', stderr='')
        with patch.object(report.subprocess, 'run', return_value=success) as run:
            self.assertEqual(report.test_clones(files, 'v1.0.0', 55), [])
        inputs = run.call_args.kwargs['input']
        self.assertIn('/internal/testutil/fixture.go\n', inputs)
        self.assertIn('/internal/testsupport/harness.go\n', inputs)
        self.assertNotIn('/internal/production.go', inputs)

    def test_rejects_command_argument_injection_before_execution(self):
        with patch.object(report.subprocess, 'run') as run, patch.object(report.subprocess, 'check_output') as check:
            for ref in ('--help', '-cfoo', 'HEAD\n--help', 'HEAD --help'):
                with self.subTest(ref=ref), self.assertRaises(ValueError):
                    report.snapshot(ref)
            for version in ('--help', 'latest', 'v1.0.0 --help', '../tool', 'v١.٢.٣'):
                with self.subTest(version=version), self.assertRaises(ValueError):
                    report.test_clones([], version, 55)
            for threshold in ('--help', '55 --help', 0, -1):
                with self.subTest(threshold=threshold), self.assertRaises(ValueError):
                    report.test_clones([], 'v1.0.0', threshold)
            run.assert_not_called()
            check.assert_not_called()

    def test_signed_deltas_and_revision_identity(self):
        with patch.object(report, 'snapshot', side_effect=[('base-sha', [('a.go', b'100644', b'a\nb\n')], 0), ('head-sha', [('a.go', b'100644', b'a\n')], 1)]), patch.object(report, 'test_clones', return_value=[]):
            result = report.build_report('base', 'head', 'v1.0.0', 55)
        self.assertEqual(result['baseline'], 'base-sha')
        self.assertEqual(result['head'], 'head-sha')
        self.assertEqual(result['delta']['production']['physical_lines'], -1)
        self.assertEqual(result['submodules'], dict(baseline=0, head=1))
        self.assertFalse(result['test_duplication']['blocking'])


if __name__ == '__main__':
    unittest.main()
